config/routes.rb
RhuiHealth::Application.routes.draw do
  resources :instances


  put "tasks/sync_aws_forum_ip_ranges"

  resources :aws_regions
  resources :home

  mount Resque::Server, :at => "/resque"

  root :to => "home#index"
end

app/models/aws_region.rb
class AwsRegion
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :ip_ranges, type: Array
  field :last_aws_forum_check, type: DateTime
  field :last_aws_forum_post, type: DateTime
end

app/models/instance.rb
class Instance
  include Mongoid::Document
  field :role, type: String
  field :region, type: String
  field :hostname, type: String
  field :ec2_public_hostname, type: String
  field :ssh_key, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/aws_regions_controller.rb
class AwsRegionsController < ApplicationController
  # GET /aws_regions
  # GET /aws_regions.json
  def index
    @aws_regions = AwsRegion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @aws_regions }
    end
  end

  # GET /aws_regions/1
  # GET /aws_regions/1.json
  def show
    @aws_region = AwsRegion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @aws_region }
    end
  end

  # GET /aws_regions/new
  # GET /aws_regions/new.json
  def new
    @aws_region = AwsRegion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @aws_region }
    end
  end

  # GET /aws_regions/1/edit
  def edit
    @aws_region = AwsRegion.find(params[:id])
  end

  # POST /aws_regions
  # POST /aws_regions.json
  def create
    @aws_region = AwsRegion.new(params[:aws_region])

    respond_to do |format|
      if @aws_region.save
        format.html { redirect_to @aws_region, notice: 'Aws region was successfully created.' }
        format.json { render json: @aws_region, status: :created, location: @aws_region }
      else
        format.html { render action: "new" }
        format.json { render json: @aws_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /aws_regions/1
  # PUT /aws_regions/1.json
  def update
    @aws_region = AwsRegion.find(params[:id])

    respond_to do |format|
      if @aws_region.update_attributes(params[:aws_region])
        format.html { redirect_to @aws_region, notice: 'Aws region was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @aws_region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aws_regions/1
  # DELETE /aws_regions/1.json
  def destroy
    @aws_region = AwsRegion.find(params[:id])
    @aws_region.destroy

    respond_to do |format|
      format.html { redirect_to aws_regions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  # GET /instances
  # GET /instances.json
  def index
    @instances = Instance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instances }
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @instance = Instance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/new
  # GET /instances/new.json
  def new
    @instance = Instance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/1/edit
  def edit
    @instance = Instance.find(params[:id])
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(params[:instance])

    respond_to do |format|
      if @instance.save
        format.html { redirect_to @instance, notice: 'Instance was successfully created.' }
        format.json { render json: @instance, status: :created, location: @instance }
      else
        format.html { render action: "new" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instances/1
  # PUT /instances/1.json
  def update
    @instance = Instance.find(params[:id])

    respond_to do |format|
      if @instance.update_attributes(params[:instance])
        format.html { redirect_to @instance, notice: 'Instance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance = Instance.find(params[:id])
    @instance.destroy

    respond_to do |format|
      format.html { redirect_to instances_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def sync_aws_forum_ip_ranges
    check_aws = CheckAWSRegionIpRanges.new
    check_aws.check_aws_forum
    check_aws.update_db
    render :json => {
      "status" => "success",
      "posted_on" => check_aws.posted_on
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aws_regions/_form.html.erb
<%= form_for(@aws_region) do |f| %>
  <% if @aws_region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aws_region.errors.count, "error") %> prohibited this aws_region from being saved:</h2>

      <ul>
      <% @aws_region.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aws_regions/edit.html.erb
<h1>Editing aws_region</h1>

<%= render 'form' %>

<%= link_to 'Show', @aws_region %> |
<%= link_to 'Back', aws_regions_path %>

app/views/aws_regions/index.html.erb
<h1>Listing aws_regions</h1>


<div id="aws_forum_sync">
  <button id="aws_forum_sync_button" class="btn btn-info"> Sync with AWS Forums IP Range Post </button>
  <div id="aws_forum_sync_status"></div>
</div>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aws_regions.each do |aws_region| %>
  <tr>
    <td><%= link_to aws_region.name, aws_region %></td>
  </tr>
<% end %>
</table>

<br />

app/views/aws_regions/new.html.erb
<h1>New aws_region</h1>

<%= render 'form' %>

<%= link_to 'Back', aws_regions_path %>

app/views/aws_regions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @aws_region.name %>
</p>
<p>
  <b>Description:</b>
  <%= @aws_region.description %>
</p>
<p>
  <b> Last Check:</b>
  <%= @aws_region.last_aws_forum_check.strftime("%B %d at %I:%M %p") %>
</p>
<p>
  <b> Last Post: </b>
  <%= @aws_region.last_aws_forum_post.strftime("%B %d at %I:%M %p") %>
</p>
<p>
  <b>IP Ranges:</b>
  <% @aws_region.ip_ranges.each do |r| %>
    </br><%= r %>
  <% end %>
</p>


<%= link_to 'Edit', edit_aws_region_path(@aws_region) %> |
<%= link_to 'Back', aws_regions_path %>

app/views/home/index.html.erb
<h1> Welcome to RHUI Health Monitoring </h1>
<a href="/aws_regions">AWS Regions</a> </br>
<a href="/instances">RHUI Server Instances</a> </br>

app/views/instances/_form.html.erb
<%= form_for(@instance) do |f| %>
  <% if @instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance.errors.count, "error") %> prohibited this instance from being saved:</h2>

      <ul>
      <% @instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :role %><br />
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :region %><br />
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :hostname %><br />
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :ec2_public_hostname %><br />
    <%= f.text_field :ec2_public_hostname %>
  </div>
  <div class="field">
    <%= f.label :ssh_key %><br />
    <%= f.text_field :ssh_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instances/edit.html.erb
<h1>Editing instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance %> |
<%= link_to 'Back', instances_path %>

app/views/instances/index.html.erb
<h1>Listing instances</h1>

<table>
  <tr>
    <th>Role</th>
    <th>Region</th>
    <th>Hostname</th>
    <th>Ec2 public hostname</th>
    <th>Ssh key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instances.each do |instance| %>
  <tr>
    <td><%= instance.role %></td>
    <td><%= instance.region %></td>
    <td><%= instance.hostname %></td>
    <td><%= instance.ec2_public_hostname %></td>
    <td><%= instance.ssh_key %></td>
    <td><%= link_to 'Show', instance %></td>
    <td><%= link_to 'Edit', edit_instance_path(instance) %></td>
    <td><%= link_to 'Destroy', instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instance', new_instance_path %>

app/views/instances/new.html.erb
<h1>New instance</h1>

<%= render 'form' %>

<%= link_to 'Back', instances_path %>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Role:</b>
  <%= @instance.role %>
</p>

<p>
  <b>Region:</b>
  <%= @instance.region %>
</p>

<p>
  <b>Hostname:</b>
  <%= @instance.hostname %>
</p>

<p>
  <b>Ec2 public hostname:</b>
  <%= @instance.ec2_public_hostname %>
</p>

<p>
  <b>Ssh key:</b>
  <%= @instance.ssh_key %>
</p>


<%= link_to 'Edit', edit_instance_path(@instance) %> |
<%= link_to 'Back', instances_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "App_Name" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "App_Name" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/tasks/sync_aws_forum_ip_ranges.html.erb
<h1>Tasks#sync_aws_forum_ip_ranges</h1>
<p>Find me in app/views/tasks/sync_aws_forum_ip_ranges.html.erb</p>